SELECT DEPTNO,JOB ,AVG(SAL)
FROM EMP
GROUP BY DEPTNO, JOB
WHERE JOB = MANAGER ;

EMP의 COMM값이 NULL이 아니고
EMP의 SAL값이 1000 이상인 데이터를
DEPTNO 테이블과 합쳐주세요
(EMP는 E, DEPT는 D로 별명지어주기)
(열은 아래 그림과 같이 출력해주세요)

SELECT E.EMPNO, E.ENAME, E.SAL, E.COMM, E.DEPTNO, D.DNAME, D.LOC
FROM EMP E ,DEPT D
WHERE E.DEPTNO = D.DEPTNO AND
WHERE E.COMM IS NOT NULL AND 
WHERE SAL >=1000 ;

SELECT E.EMPNO, E.ENAME, E.SAL, E.COMM,DEPTNO, D.DNAME, D.LOC
FROM EMP E JOIN DEPT D USING (DEPTNO)
WHERE E.SAL >= 1000 
AND  E.COMM IS NOT NULL
ORDER BY DEPTNO, E.EMPNO
 ;
 
SELECT DEPTNO,JOB ,AVG(SAL)
FROM EMP
GROUP BY DEPTNO , JOB
HAVING JOB = 'MANAGER' ;

--EMP 테이블의 DEPTNO별로 SAL의 최대값을 가진 데이터를 구해서
DEPTNO 테이블과 합쳐줘서 아래 그림처럼 만들어 주기 위해
빈칸에 들어가야 할 것은? (서브쿼리)

SELECT E.EMPNO, E.ENAME, E.SAL, E.COMM, D.DEPTNO, D.DNAME, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND E.SAL IN ( SELECT SAL FROM EMP 
WHERE SAL BETWEEN 2800 AND 5000) ;




SELECT E.EMPNO, E.ENAME, E.SAL, E.COMM, D.DEPTNO, D.DNAME, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND E.SAL IN ( SELECT SAL FROM EMP 
WHERE SAL =2850 , 
WHERE SAL BETWEEN 3000 AND 5000) ;
