DROP USER MADANG CASCADE;

CREATE USER MADANG
IDENTIFIED BY MADANG;

DROP USER ORCLSTUDY ;
CREATE USER ORCLSTUDY 
IDENTIFIED BY 1234;


grant CREATE SESSION TO madang;
-- 마당 유저 만들기  권한 주기 

GRANT CREATE SESSION TO MADANG ;
GRANT CONNECT , RESOURCE TO MADANG  ; 
GRANT CREATE VIEW, CREATE SYNONYM TO MADANG ;

 \